#!/bin/bash
ls -1ap | awk '{gsub(/[^[:alnum:]./]/,"&\n"); print}' | awk '{if ($0 == "./" || $0 == "../") print $0; else print $0","}' | sort -df | tr '\n' ',' | sed 's/,$/\n/' | sed 's/\.\.\///g' | sed 's/\.\///g' | sed 's/\//\//g' | awk '{gsub(/[[:space:]]/,"&\n"); print}'

