#!/usr/bin/env bash
# This is a bash script display "best school" 10 times using until loop
#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1

until [ $counter -gt 10 ]
do
	echo "Best School"
	((counter++))
done
