#!/usr/bin/env bash
# This bash script is displaying "Best School" 10 times at 9 it will print Hi

counter=1

while [[ $counter -le 10 ]]
do
	if [ $counter -eq 9 ]
	then 
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
